/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */ package examples

import io.github.serpro69.kfaker.faker
import org.apache.commons.lang3.RandomUtils.nextInt
import java.time.LocalDate
import java.time.LocalDate.now
import kotlin.reflect.full.memberProperties


fun main() {
    val renderer = TemplateRenderer()
    val pdfGenerator = PdfGenerator()
    val invoice = Invoice()
    val contextValues = mapOf("invoice" to invoice, "items" to invoice.lineItems)
    val message = renderer.render("invoice.html", contextValues)
    pdfGenerator.generate(message)
}


val f = faker { }

data class Invoice(
    val number: Number = nextInt(1, 10),
    val date: LocalDate = now(),
    val dueDate: LocalDate = now().plusDays(15),
    val logoUrl: String = "https://rillet.io/signature.png",
    val websiteUrl: String = "https://rillet.io",
    val companyName: String = f.company.name(),
    val companyAddress: String = f.address.fullAddress(),
    val companyEmail: String = f.internet.email(),
    val invoicedCompany: String = f.company.name(),
    val invoicedAddress: String = f.address.fullAddress(),
    val invoicedEmail: String = f.internet.email(),
    val lineItems: List<LineItem> = List(nextInt(1, 4)) { LineItem() }
)

data class LineItem(
    val description: String = f.commerce.productName(),
    val unitPrice: Double = f.random.nextDouble(),
    val amount: Int = f.random.nextInt(1, 5)
) {
    val totalPrice: Double
        get() = unitPrice * amount
}

inline fun <reified T : Any> T.asMap(): Map<String, Any> {
    val props = T::class.memberProperties.associateBy { it.name }
    return props.keys.associateWith {
        props[it]!!.call(this)!!
    }
}