/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package examples

fun main() {
    val reportsPersonnel = List(5) { Report.random() }
    val categoryPersonnel = ReportCategory("COGS Personnel", reportsPersonnel)
    val reportsGoS = MutableList<Visitable>(2) { Report.random() }.apply { add(categoryPersonnel) }
    val categoryGoS = ReportCategory("Cost of Goods Sold", reportsGoS)
    val visitor = Visitor()
    categoryGoS.accept(visitor)
    visitor.save("test.xlsx")

}
